### ISSUE TITLE
1주차 회고

### ISSUE THREAD

**Issue by Kwakcena** [CodeSoom/project-react-1-Kwakcena#6]
# 내가 한 것(Fact)
- #1 의 내용들을 수행했습니다.
- 5가지의 task가 있었지만, 3가지 밖에 수행하지 못했습니다.
- `json-server` 를 이용해 가짜 서버를 만들고 데이터를 불러오기.
- `redux` 를 이용해 가짜 서버로부터 아이템을 불러들여 화면에 render 하기.
- render 된 product 들을 card list 형태의 UI를 갖도록 layout 구성하기.
- 각각의 상품들은 notion 링크를 걸어 임시 상세 페이지를 구성하기.

# 느낀 점(Feelings)
- 프로젝트를 기획하는 것 부터 힘들었습니다. 어떤 프로젝트를 해야 할지, 무엇을 해야 포트폴리오로 좋을지 아무런 생각도 나지 않았습니다.
- 고심 끝에 고른 당근마켓 클론이라는 주제는 그닥 마음에 들지 않았습니다. 진행하고 있는 현재도 어떻게 시작해야 할지 감이 안잡히고 내가 할 수 있는 프로젝트인지 잘 모르겠습니다. 이런 프로젝트 경험이 없어서 그런지 자신감이 생기지가 않습니다.
- 그래서 그런지 하기가 싫어졌습니다. 오히려 알고리즘 문제를 푸는데에 집중하고 취업에 프로젝트가 꼭 필요함에도 불구하고 이렇게 악순환을 또 반복하였습니다.
- 분명히 했던 방식인데 생각이 잘 나지 않는 경우가 많았습니다. 예전에 한 내용을 복사해서 붙여넣으면서 붙여넣을 자료가 없었다면 아무것도 못했을거란 생각이 머리속을 맴돌았습니다.

# 배운 점(Finding)
- `json-server` 를 이용해 가짜 서버를 만들어 보기.
- `facepaint` 라이브러리를 이용하여 반응형 페이지 만들기

# 내가 할 것(Affirmation)
- 내 프로젝트에 필요한 예제들을 따라해보면서 자신감을 찾는게 우선일 것 같습니다.

**Comment by hannut91** [comment]
음.. 일단 자신이 만들고 싶은 것을 찾는 것도 중요하지만 일단 한번 해보는 것도 괜찮을 것 같아요. ㅎㅎ 한 번 프로젝트를 해본 자신감이 있으면 나중에 무엇이든지 만들고 싶은게 생각날수도 있거든요. 만들고 싶은게 있어서 배우는 것보다 사실은 저는 배우고 났더니 만들고 싶은게 생긴다고 생각하거든요.
